export interface LolAccount{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    rank: string,
    champions: number,
    skins: number,
    title: string,
    description: string,
    price: number,
    currency: string,
    deliveryTime: number,
    stock: number,
    active: boolean,
    updatedAt: string,
}

export interface LolBoost{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    desiredRank: string,
    title: string,
    description: string,
    price: number,
    currency: string,
    deliveryTime: number,
    stock: number,
    duration: number,
    serviceType: string,
    active: boolean,
    updatedAt: string,
}

export interface LolCoach{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    rank: string,
    title: string,
    description: string,
    price: number,
    currency: string,
    deliveryTime: number,
    stock: number,
    duration: number,
    active: boolean,
    updatedAt: string,
}

export interface LolRP{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    title: string,
    description: string,
    price: number,
    currency: string,
    deliveryTime: number,
    stock: number,
    value: number,
    active: boolean,
    updatedAt: string,
}

