export interface ValorantAccount{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    rank: string,
    agents: number,
    skins: number,
    title: string,
    description: string,
    price: number,
    currency: string,
    deliveryTime: number,
    stock: number,
    active: boolean,
    updatedAt: string,
}

export interface ValorantBoost{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    desiredRank: string,
    title: string,
    description: string,
    price: number,
    currency: string,
    active: boolean,
    deliveryTime: number,
    stock: number,
    duration: number,
    serviceType: string,
    updatedAt: string,
}

export interface ValorantCoach{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    rank: string,
    title: string,
    description: string,
    price: number,
    currency: string,
    active: boolean,
    deliveryTime: number,
    stock: number,
    duration: number,
    updatedAt: string,
}

export interface ValorantVP{
    _id: string,
    categoryName: string,
    serviceName: string,
    sellerId:string,
    server: string,
    title: string,
    description: string,
    price: number,
    currency: string,
    active: boolean,
    deliveryTime: number,
    stock: number,
    updatedAt: string,
}